services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_RAZORPAY_KEY_ID: ${VITE_RAZORPAY_KEY_ID}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    container_name: myapp-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    # restart: always

  backend:
    image: professorsergio12/myapp-backend:latest
    container_name: myapp-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  worker-server:
    image: professorsergio12/myapp-worker-server:latest
    container_name: myapp-worker-server
    env_file:
      - ./worker-server/.env
    restart: unless-stopped
