version: '3'

services:
  frontend:
    build: ./frontend
    image: frontend-image
    container_name: frontend-container
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    image: backend-image
    container_name: backend-container
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  worker-server:
    build: ./worker-server
    image: worker-server-image
    container_name: worker-server-container
    env_file:
      - ./worker-server/.env
    restart: unless-stopped