name: Deploy Musafir App to EC2

on:
  push:
    branches: ["aws-server"] # Only trigger for this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check current directory
        run: |
          echo "Current directory: $(pwd)"

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Build & Push All Images via Docker Compose
      - name: Build & Push Docker Images
        run: |
          docker compose build
          docker compose push

      # 4. Deploy to EC2
     
