name: Deploy Musafir App to EC2

on:
  push:
    branches: ["aws-server"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check current directory
        run: |
          echo "Current directory: $(pwd)"

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Build & Push Frontend
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/musafir-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/musafir-frontend:latest

      # 4. Build & Push Backend
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/musafir-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/musafir-backend:latest

      # 5. Build & Push Worker
      - name: Build & Push Worker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/musafir-worker:latest ./worker-server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/musafir-worker:latest

     
