name: Deploy Musafir App to EC2

on:
  push:
    branches: ["aws-server"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Images (CI)
        run: |
          docker compose -f docker-compose.ci.yml build
          docker compose -f docker-compose.ci.yml push

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "MUSAFIR-Exommerce" ]; then
              echo "Cloning repository..."
              git clone https://github.com/professorSergio12/MUSAFIR-Exommerce.git
            else
              echo "Updating repository..."
              cd MUSAFIR-Exommerce
              git pull
              cd ..
            fi

            cd MUSAFIR-Exommerce

            echo "Pulling backend & worker images..."
            docker compose pull myapp-backend myapp-worker-server

            echo "Building frontend with EC2 .env..."
            docker compose build --no-cache frontend

            echo "Restarting containers..."
            docker compose down
            docker compose up -d

            echo "Deployment Complete âœ…"
